---
name: Repository Dispatch Job
on:
  repository_dispatch:
    types: [build]
#  schedule:
#    - cron: '*/5 * * * *'
#    - cron: '*/6 * * * *'
jobs:
  run-shell-commands_every_2nd_minute:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Job example
        run: echo " Hello World from a schedule action"
