---
name: Pull Request_Shell Commands
on:
  pull_request:
    types: [closed, assigned, opened, reopened]
jobs:
  run-shell-commands_on_PULL_REQUEST:
    runs-on: ubuntu-latest
    steps:
      - name: Pull_request example
        run: echo " Hello World from a pull request event"
      - name: echo a multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-commands"]
    steps: 
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
