name: This is a TASK

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Kindly provide you name -'
        default: 'Owner'
        required: true

jobs:

  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Starting of Pipeline
        run: echo "Hello ${{ inputs.name }}"
  Build:
    needs: [Hello]
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: echo Hello, world!
    
  Staging:
    name: Deploy to Staging 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  Prod:
    name: Deploy to Prod
    needs: [Staging]
    runs-on: ubuntu-latest
    environment: 
      name: Prod
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
